apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-etl
  namespace: devops-case
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: python-etl
              image: goyash/devops-case-python:latest
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
