apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-case
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: goyash/devops-case-backend:latest
          ports:
            - containerPort: 5050
          env:
            - name: ATLAS_URI
              valueFrom:
                secretKeyRef:
                  name: atlas-secret
                  key: ATLAS_URI
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5050
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5050
            initialDelaySeconds: 10
            periodSeconds: 5
